// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/zone-visual/ZoneMap.tsx": () => import("../components/mockups/zone-visual/ZoneMap.tsx"),
  "./components/mockups/palette-explorer/PaletteExplorer.tsx": () => import("../components/mockups/palette-explorer/PaletteExplorer.tsx")
};
